name: Docker

on:
  workflow_dispatch:

jobs:
   push:
    runs-on: ubuntu-latest
    
    steps:

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin         
